title: "Deeja Chhabra"
author: "Deeja Chhabra"
description: "Made with a lot of code.<b style=\"color: #f45;\">Just Kidding</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: False        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: False        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title : "Resume", file: "Deeja_Resume.pdf"}
  - {title : "Blog" , file : "blog.md" }
  - {title : "Education", file: "educ.md" }
  - {title : "Projects", file: "projects.md" }

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:chhabradeeja@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/deejachhabra"}
  - {title: linkedin, icon: linkedin , url: "https://www.linkedin.com/in/deejachhabra"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
